### ISSUE TITLE
Missing nl or out of sync content from "LisaFC" version of config.toml

### ISSUE THREAD

**Issue by RichieEscarez** [LisaFC/docsysite#20]
https://github.com/LisaFC/docsysite/blob/f4a9aa2c612b7847449a5c18300f1beea8619724/config.toml#L75

The getting started docs mention to remove the NL content but its not in this version of the config.toml:
https://serene-roentgen-10fbaa.netlify.com/docs/getting-started/#basic-site-configuration

Also, the Google Search section in the doc says its enabled by default (but its commented out in this new draft)

**Comment by LisaFC** [comment]
Yep, I'm going to try and create a consolidated version of config.toml for Goldydocs and have that be "canon". This isn't specifically the version we're asking users to copy so I'm less worried about it....

**Comment by RichieEscarez** [comment]
Ok, sounds good. I just expected this whole "testing" repo as the replacement for google/docsy. Should I leave this open as a reminder, otherwise we can close?
