### ISSUE TITLE
Broken Example Site and GitHub links in "main" menu

### ISSUE THREAD

**Issue by RichieEscarez** [LisaFC/docsysite#3]
The main menu links can only be relative to BaseURL (mentioned in the box under: https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu)

**Comment by RichieEscarez** [comment]
Not sure if its will work but maybe an opportunity to show how redirects work?

**Comment by LisaFC** [comment]
Whoah, excellent spot. Though the existing config.toml works fine locally, but it breaks when it's served from Netlify. Also that box seems to indicate that if you provide an absolute URL (which I do) it should override the baseURL, but it isn't overriding it. Kubeflow has main menu links done the same way that work fine. Let me investigate....

**Comment by LisaFC** [comment]
Fixed in https://github.com/LisaFC/docsysite/commit/278446d2fa065339c33fff79cdaed4df0c90453d

(changing baseURL from "" to "/" fixed it. I'll make the same change in Goldydocs.)
