### ISSUE TITLE
Install and update section

### ISSUE THREAD

**Issue by RichieEscarez** [LisaFC/docsysite#7]
I think there should be a formal install and update section. The [Getting Started](https://serene-roentgen-10fbaa.netlify.com/docs/getting-started/#keeping-the-theme-up-to-date) topic includes the install and update steps but I dont thing its a natural place for users to look for that info.

**Comment by LisaFC** [comment]
I think the installation stuff works fine there (I think that's where most people would look for it, and we suggest that users add installation instructions to their own Getting Started sections), but I agree the update could live in its own page.

**Comment by LisaFC** [comment]
Fixed (?) in https://github.com/LisaFC/docsysite/commit/6afdf87590952864db2788bca3f25c6c9a644665

Let me know what you think!

**Comment by RichieEscarez** [comment]
Ive opened a PR for adding more detail to the update page: https://github.com/LisaFC/docsysite/pull/11
